version: '3.7'

services:
  webapp:
    container_name: hb-webapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    env_file:
      .env
    # environment:
    #   - NODE_ENV=development
    #   - CHOKIDAR_USEPOLLING=true